server:
  port: 8001
spring:
  application:
    name: moss-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true